-- DROP ------------------------------------------------------------------------
DROP TABLE CAR;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE OFFER;
DROP TABLE PAYMENT;
DROP SEQUENCE CUSTOMER_SEQUENCE;
DROP SEQUENCE EMPLOYEE_SEQUENCE;
DROP SEQUENCE CAR_SEQUENCE;
DROP SEQUENCE OFFER_SEQUENCE;
DROP SEQUENCE PAYMENT_SEQUENCE;
DROP PROCEDURE INSERT_CUSTOMER;
DROP PROCEDURE INSERT_EMPLOYEE;
DROP PROCEDURE INSERT_CAR;
DROP PROCEDURE INSERT_PAYMENT;
DROP PROCEDURE INSERT_OFFER;

-- SEQUENCES -------------------------------------------------------------------
CREATE SEQUENCE CUSTOMER_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE EMPLOYEE_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE CAR_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE OFFER_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE PAYMENT_SEQUENCE
START WITH 1000
INCREMENT BY 1;

-- CREATE TABLES ---------------------------------------------------------------
CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(16) PRIMARY KEY,
    CUSTOMER_FIRST_NAME VARCHAR2(32),
    CUSTOMER_LAST_NAME VARCHAR2(32),
    CUSTOMER_USERNAME VARCHAR2(32),
    CUSTOMER_PASSWORD VARCHAR2(64)
);
CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID NUMBER(16) PRIMARY KEY,
    EMPLOYEE_FIRST_NAME VARCHAR2(32),
    EMPLOYEE_LAST_NAME VARCHAR2(32),
    EMPLOYEE_USERNAME VARCHAR2(32),
    EMPLOYEE_PASSWORD VARCHAR2(64)
);
CREATE TABLE CAR(
    CAR_ID NUMBER(16) PRIMARY KEY,
    CAR_YEAR NUMBER(4),
    CAR_MAKE VARCHAR2(32),
    CAR_MODEL VARCHAR2(32),
    CAR_MILEAGE NUMBER(8),
    CAR_PRICE NUMBER(9,2),
    CAR_BALANCE NUMBER(9,2),
    OWNER_ID NUMBER(16),
    
    CONSTRAINT FK_CUSTOMER_CAR
    FOREIGN KEY (OWNER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE TABLE OFFER(
    OFFER_ID NUMBER(16) PRIMARY KEY,
    OFFER_STATUS VARCHAR2(16),
    OFFER_AMOUNT NUMBER(9,2),
    CAR_ID NUMBER(16),
    CUSTOMER_ID NUMBER(16),
    
    CONSTRAINT FK_CAR_OFFER
    FOREIGN KEY (CAR_ID)
    REFERENCES CAR(CAR_ID),
    CONSTRAINT FK_CUSTOMER_OFFER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE TABLE PAYMENT(
    PAYMENT_ID NUMBER(16) PRIMARY KEY,
    PAYMENT_AMOUNT NUMBER(9,2),
    CAR_ID NUMBER(16),
    CUSTOMER_ID NUMBER(16),
    
    CONSTRAINT FK_CAR_PAYMENT
    FOREIGN KEY (CAR_ID)
    REFERENCES CAR(CAR_ID),
    CONSTRAINT FK_CUSTOMER_PAYMENT
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- STORED PROCEDURES -----------------------------------------------------------
CREATE OR REPLACE PROCEDURE INSERT_CUSTOMER(
    CUSTOMER_FIRST_NAME IN VARCHAR2,
    CUSTOMER_LAST_NAME IN VARCHAR2,
    CUSTOMER_USERNAME IN VARCHAR2,
    CUSTOMER_PASSWORD IN VARCHAR2)
AS
BEGIN
    INSERT INTO CUSTOMER VALUES(
        CUSTOMER_SEQUENCE.NEXTVAL,
        CUSTOMER_FIRST_NAME,
        CUSTOMER_LAST_NAME,
        CUSTOMER_USERNAME,
        CUSTOMER_PASSWORD);
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE INSERT_EMPLOYEE(
    EMPLOYEE_FIRST_NAME IN VARCHAR2,
    EMPLOYEE_LAST_NAME IN VARCHAR2,
    EMPLOYEE_USERNAME IN VARCHAR2,
    EMPLOYEE_PASSWORD IN VARCHAR2)
AS
BEGIN
    INSERT INTO EMPLOYEE VALUES(
        EMPLOYEE_SEQUENCE.NEXTVAL,
        EMPLOYEE_FIRST_NAME,
        EMPLOYEE_LAST_NAME,
        EMPLOYEE_USERNAME,
        EMPLOYEE_PASSWORD);
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE INSERT_CAR(
    CAR_YEAR IN NUMBER,
    CAR_MAKE IN VARCHAR2,
    CAR_MODEL IN VARCHAR2,
    CAR_MILEAGE IN NUMBER,
    CAR_PRICE IN NUMBER,
    CAR_BALANCE IN NUMBER,
    OWNER_ID IN NUMBER)
AS
BEGIN
    INSERT INTO CAR VALUES(
        CAR_SEQUENCE.NEXTVAL,
        CAR_YEAR,
        CAR_MAKE,
        CAR_MODEL,
        CAR_MILEAGE,
        CAR_PRICE,
        CAR_BALANCE,
        OWNER_ID);
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE INSERT_PAYMENT(
    PAYMENT_AMOUNT IN NUMBER,
    CAR_ID IN NUMBER,
    CUSTOMER_ID IN NUMBER)
AS
BEGIN
    INSERT INTO PAYMENT VALUES(
        PAYMENT_SEQUENCE.NEXTVAL,
        PAYMENT_AMOUNT,
        CAR_ID,
        CUSTOMER_ID);
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE INSERT_OFFER(
    OFFER_STATUS IN VARCHAR2,
    OFFER_AMOUNT IN NUMBER,
    CAR_ID IN NUMBER,
    CUSTOMER_ID IN NUMBER)
AS
BEGIN
    INSERT INTO OFFER VALUES(
        OFFER_SEQUENCE.NEXTVAL,
        OFFER_STATUS,
        OFFER_AMOUNT,
        CAR_ID,
        CUSTOMER_ID);
    COMMIT;
END;
/
