-- DROP
DROP TABLE CAR;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE OFFER;
DROP TABLE PAYMENT;
DROP SEQUENCE CUSTOMER_SEQUENCE;
DROP SEQUENCE EMPLOYEE_SEQUENCE;
DROP SEQUENCE CAR_SEQUENCE;
DROP SEQUENCE OFFER_SEQUENCE;
DROP SEQUENCE PAYMENT_SEQUENCE;

-- CREATE TABLES
CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(16) PRIMARY KEY,
    CUSTOMER_FIRST_NAME VARCHAR2(32),
    CUSTOMER_LAST_NAME VARCHAR2(32),
    CUSTOMER_USERNAME VARCHAR2(32),
    CUSTOMER_PASSWORD VARCHAR2(64)
);
CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID NUMBER(16) PRIMARY KEY,
    EMPLOYEE_FIRST_NAME VARCHAR2(32),
    EMPLOYEE_LAST_NAME VARCHAR2(32),
    EMPLOYEE_USERNAME VARCHAR2(32),
    EMPLOYEE_PASSWORD VARCHAR2(64)
);
CREATE TABLE CAR(
    CAR_ID NUMBER(16) PRIMARY KEY,
    CAR_YEAR NUMBER(4),
    CAR_MAKE VARCHAR2(32),
    CAR_MODEL VARCHAR2(32),
    CAR_MILEAGE NUMBER(8),
    CAR_PRICE NUMBER(9,2),
    CAR_BALANCE NUMBER(9,2),
    OWNER_ID NUMBER(16),
    
    CONSTRAINT FK_CUSTOMER_CAR
    FOREIGN KEY (OWNER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE TABLE OFFER(
    OFFER_ID NUMBER(16) PRIMARY KEY,
    OFFER_STATUS VARCHAR2(16),
    OFFER_AMOUNT NUMBER(9,2),
    CAR_ID NUMBER(16),
    CUSTOMER_ID NUMBER(16),
    
    CONSTRAINT FK_CAR_OFFER
    FOREIGN KEY (CAR_ID)
    REFERENCES CAR(CAR_ID),
    CONSTRAINT FK_CUSTOMER_OFFER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE TABLE PAYMENT(
    PAYMENT_ID NUMBER(16) PRIMARY KEY,
    PAYMENT_AMOUNT NUMBER(9,2),
    CAR_ID NUMBER(16),
    CUSTOMER_ID NUMBER(16),
    
    CONSTRAINT FK_CAR_PAYMENT
    FOREIGN KEY (CAR_ID)
    REFERENCES CAR(CAR_ID),
    CONSTRAINT FK_CUSTOMER_PAYMENT
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- SEQUENCES
CREATE SEQUENCE CUSTOMER_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE EMPLOYEE_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE CAR_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE OFFER_SEQUENCE
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE PAYMENT_SEQUENCE
START WITH 1000
INCREMENT BY 1;
